//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

   //
   // void Auto class visitors
   //

   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( Housedeclarations() )*
    * f1 -> ( facts() )*
    * f2 -> <EOF>
    */
   public void visit(Goal n);

   /**
    * f0 -> <HOUSE_NAME>
    * f1 -> <NAME>
    * f2 -> ";"
    */
   public void visit(Housedeclarations n);

   /**
    * f0 -> <NAME>
    * f1 -> <OPERATOR>
    * f2 -> <NAME>
    * f3 -> ";"
    */
   public void visit(facts n);

}

